### ISSUE TITLE
Parses "cloves" ingredient incorrectly

### ISSUE THREAD

**Issue by boxydog** [strangetom/ingredient-parser#11]
Parses "1 tsp cloves" as an amount "1 tsp clove" with no ingredient. Should be "cloves" as an ingredient.

<img width="827" alt="image" src="https://github.com/strangetom/ingredient-parser/assets/93335439/182be7f3-9c65-40e3-8bba-33b1cacd7049">

**Comment by strangetom** [comment]
This one has caused a lot of problems, and I thought I'd solved it but clearly not. Training a model from the latest develop branch seems to do the right thing now, so it will be fixed in the next release. I'll write some tests to make sure it doesn't get missed again.

**Comment by strangetom** [comment]
0e4246732f add some tests to check that the various uses of "cloves" are parsed correctly. 
cf65f1687d adds a new model that passes these tests.

This is still in the develop branch for now, but I'll close this issue as completed.
