### ISSUE TITLE
NLTK

### ISSUE THREAD

**Issue by marcosfelt** [strangetom/ingredient-parser#5]
Thanks for this package!  It might be good to run the following code on startup, so users don't run into an error:

```
 import nltk
 nltk.download('averaged_perceptron_tagger')
```

**Comment by strangetom** [comment]
Hi @marcosfelt. Thanks for the suggestion. 

I've added a check that runs when the library is imported that will download the nltk resources if it can't find the ones it needs. See d975215b14322379fbfb2f1bb029c053ae234107. This will be in the next release.

**Comment by marcosfelt** [comment]
Thanks!
